# Generated by Django 4.2.7 on 2025-12-25 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Necha marta ko‘rish/yuklash mumkin', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='expire_date',
            field=models.DateTimeField(blank=True, help_text='Shu sanadan keyin link ishlamaydi', null=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='notice',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
