# Generated by Django 4.2.7 on 2025-12-25 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_notice_download_limit_notice_expire_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='public_views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='notice',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
