# Generated by Django 4.2.7 on 2025-12-25 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_notice_public_views_alter_notice_download_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='notice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='download_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Public link orqali nechta odam ko‘ra oladi', null=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='expire_date',
            field=models.DateTimeField(blank=True, help_text='Shu sanadan keyin link ishlamaydi', null=True),
        ),
    ]
